### ISSUE TITLE
Error: Could not symlink lib/haxe/extra /usr/local/lib/haxe is not writable.

### ISSUE THREAD

**Issue by MatthijsKamstra** [HaxeFoundation/homebrew-haxe#1]
Not sure I am submitting the brew errors correctly here, but perhaps you could point me in the right direction if I am wrong.

I tried to install haxe via brew:
`brew reinstall haxe --HEAD`

I got

```
...
/bin/sh: line 1: 54001 Segmentation fault: 11  nekotools boot run.n
make: *** [haxelib] Error 139
Error: Could not symlink lib/haxe/extra
/usr/local/lib/haxe is not writable.
```

the normal method installs an older version:

```
brew install haxe
Warning: haxe-3.2.1 already installed, it's just not linked
```

The instructions are also mentioned on the website: https://haxe.org/documentation/introduction/building-haxe.html

**Comment by andyli** [comment]
Next time you may submit to https://github.com/Homebrew/homebrew-core

It looks like you've a previous haxe installation that was installed using sudo (or used the Mac installer). Try remove the existing version manually before re-installing.

**Comment by andyli** [comment]
Hopefully it has been resolved. Please resubmit to `homebrew/homebrew-core` otherwise.

**Comment by MatthijsKamstra** [comment]
no it didn't but will submit to brew : thx
