### ISSUE TITLE
Formulae install only old versions of haxe

### ISSUE THREAD

**Issue by hn3000** [HaxeFoundation/homebrew-haxe#2]
The formulae in this repository install only some older versions of haxe (-snapshot is 3.3.0, everything else is what it says).

Wouldn't it make more sense to change the README to recommend install haxe using the haxe formula included in homebrew-core (it installs the current stable version 3.4.2 now)?

**Comment by andyli** [comment]
Yeah... The readme already says `NOTE: work-in-progress` though.
Will add something to make it clearer.
